### ISSUE TITLE
Large js files cause script to timeout on shared hosting

### ISSUE THREAD

**Issue by curiousercreative** [acarbone/AssetsMinify#21]
I've got MBs of js that I'm trying to get AssetsMinify to handle, however on shared hosting it times out. Error below:
> Fatal error:  Maximum execution time of 30 seconds exceeded in /home/foradacopa/foradacopa.com/wp-content/plugins/assetsminify/lib/JSMin.php on line 280

I understand of course why this happens but I'd like to offer an idea for circumventing the problem aside from reducing the script size and increasing server resources: Include an option for exluding files that have already been minified. There's an option similar to this for excluding files, however it ends up not aggregating the scripts.

**Comment by acarbone** [comment]
As explained here https://github.com/acarbone/AssetsMinify/issues/22 - resources listed as to exclude are enqueue by wordpress but not considered from AssetsMinify.
