### ISSUE TITLE
"Resources to exclude" problem

### ISSUE THREAD

**Issue by curiousercreative** [acarbone/AssetsMinify#22]
Resources entered in this area aren't minified and aggregated, which is intended (although I'd like an option to exclude from magnification, but include in aggregation). However, excluded resources also appear to not be loaded by Wordpress at all. Not just missing from the aggregation, never being loaded.

**Comment by acarbone** [comment]
I've checked it: resources listed as to exclude are enqueue by wordpress but not considered from AssetsMinify. That is the expected behaviour.
