### ISSUE TITLE
Wrong number of brackets in minified CSS

### ISSUE THREAD

**Issue by bonny** [acarbone/AssetsMinify#26]
There is a problem with the minification of the CSS used by for example http://responsivebp.com. 

After minification at least one brace (`}`) is missing in the output.

After some digging this is the part of the CSS that is causing errors:

	@-moz-document url-prefix() {
	    /*
		 * Remove excess padding in Firefox
		 */
	  input[type="color"] {
	    min-height: 1.8em;
	    padding: 0; } }
	@media (-webkit-min-device-pixel-ratio: 0) {
	
	    /*
		 * Fix field styling on iPhone and iPad.
		 * 1. Add a select indicator
		 */
	  select {
	    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMC4wMzEiIGhlaWdodD0iMTAuNSI+PHBvbHlnb24gZmlsbD0iIzIyMiIgcG9pbnRzPSIxMSwwIDUuNSw5IDAsMCIvPjwvc3ZnPg==);
	    /* 1 */
	    background-repeat: no-repeat;
	    background-position: right center;
	    padding-right: 1.67em; }
	    [dir="rtl"] select {
	      background-position: .67em center;
	      padding-right: 0;
	      padding-left: 1.67em; } }
	

The source for this is here btw:
https://github.com/ResponsiveBP/Responsive/blob/ec1e1a2d491be47cbb8f8b45ccf80b6f45b91bfa/build/responsive.css#L3009

When minified using Assets Minify it turns into this (CSS expanded again to make it more easy to read):

	@-moz-document url-prefix() {
		input[type="color"] {
			min-height: 1.8em;
			padding: 0
		}
		@media (-webkit-min-device-pixel-ratio:0) {
			select {
				background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMC4wMzEiIGhlaWdodD0iMTAuNSI+PHBvbHlnb24gZmlsbD0iIzIyMiIgcG9pbnRzPSIxMSwwIDUuNSw5IDAsMCIvPjwvc3ZnPg==);
				background-repeat: no-repeat;
				background-position: right center;
				padding-right: 1.67em
			}
			[dir="rtl"] select {
				background-position: .67em center;
				padding-right: 0;
				padding-left: 1.67em
			}
		}
		
	
So before minification is has 5 `{` and 5 `}`. After minification it has 5 `{` but only 4 `}`, which is wrong. This behavior causes all CSS from other files etc. added after the abvove snippet to not be shown (or maybe shown for other browsers/devices with specific pixel ratio, I'm not sure).

I think the problem is that the opening brace for `@-moz-document url-prefix() {`is never closed again.

**Comment by acarbone** [comment]
Will be resolved in the next plugin's release (currently dev branch).

**Comment by bonny** [comment]
I did a quick test and it seems to be solved now in version 2.x. of the plugin. Thanks a lot!
