### ISSUE TITLE
@font-face compile bug

### ISSUE THREAD

**Issue by Tusko** [acarbone/AssetsMinify#30]
I have a code

	@font-face {

		font-family: 'Ubuntu';

		font-style: normal;

		font-weight: 300;

		src: local('Ubuntu Light'), local('Ubuntu-Light'), url(http://fonts.gstatic.com/s/ubuntu/v7/d7UcEnGHOeZ1eW8X4gtq5g.woff2) format('woff2'), url(http://fonts.gstatic.com/s/ubuntu/v7/e7URzK__gdJcp1hLJYAEag.woff) format('woff');
	}

	@font-face{

		font-family: 'fontello';
		
		src:url('fonts/fontello.eot?50994278');
		
		src:url('fonts/fontello.eot?50994278#iefix') format('embedded-opentype'),url('fonts/fontello.woff?50994278') format('woff'),url('fonts/fontello.ttf?50994278') format('truetype'),url('fonts/fontello.svg?50994278#fontello') format('svg');
		font-weight:normal;
		
		font-style:normal;
		
	}

	@media screen and (-webkit-min-device-pixel-ratio:0) {

		@font-face {
		
			font-family: 'fontello';
			
			src: url('fonts/fontello.svg?50994278#fontello') format('svg');
			
		}
		
	}

In result: 

		@font-face {font-family: 'Ubuntu';font-style: normal;font-weight: 300;src: local('Ubuntu Light'), local('Ubuntu-Light'), url(http://fonts.gstatic.com/s/ubuntu/v7/d7UcEnGHOeZ1eW8X4gtq5g.woff2) format('woff2'), url(http://fonts.gstatic.com/s/ubuntu/v7/e7URzK__gdJcp1hLJYAEag.woff) format('woff');}
	   @font-face { @font-face{font-family: 'fontello';src:url('fonts/fontello.eot?50994278');src:url('fonts/fontello.eot?50994278#iefix') format('embedded-opentype'),url('fonts/fontello.woff?50994278') format('woff'),url('fonts/fontello.ttf?50994278') format('truetype'),url('fonts/fontello.svg?50994278#fontello') format('svg');font-weight:normal;font-style:normal;} }

So that `@font-face { @font-face{` doesn't work)

P.S. In SCSS this code compile fine, in CSS I have some bug

**Comment by acarbone** [comment]
Will be resolved in the next plugin's release (currently dev branch).

**Comment by Tusko** [comment]
@acarbone still doesn't work with multisites.

it returns:

`https://domain.com/wp-content/uploads/sites/themes/themename/style/fonts/subset-500.woff`

I need:

`https://domain.com/wp-content/themes/themename/style/fonts/subset-500.woff`
