### ISSUE TITLE
Fatal error on front end after upgrade

### ISSUE THREAD

**Issue by dbisso** [acarbone/AssetsMinify#31]
Just updated one of my sites to version 2.0.1. On loading my front page, I got a fatal error:

`PHP Fatal error:  Class 'AssetsMinify' not found in [/path/to/plugins]/assetsminify/plugin.php on line 12`

I use Composer to manage my plugins and other dependencies and I think line:

```php
require 'vendor/autoload.php';
```
in [`plugin.php`](https://github.com/acarbone/AssetsMinify/blob/v2.0.1/plugin.php#L11)   is the problem. It appears to be loading the autoloader from the site root instead of the plugin's one. Replacing it with:

```php
require dirname(__FILE__) . '/vendor/autoload.php';
```

seems to work and is a bit more robust. It might be a bit of an edge case, but it should help other people who have a similar set-up.

Thanks

**Comment by acarbone** [comment]
Fixed on v2.0.2. Thanks.
